# Generated by Django 3.0.4 on 2020-04-03 17:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dtd_request.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.CharField(help_text='First Last', max_length=200, verbose_name='Your Name')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Your Email Address')),
                ('primary_phone', models.CharField(blank=True, help_text='###-###-####', max_length=17, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Phone number where you can be reached')),
                ('secondary_phone', models.CharField(blank=True, help_text='###-###-####', max_length=17, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Backup phone number')),
                ('add_info', models.TextField(help_text="Share anything else you'd like for us to know", verbose_name='Please provide any additional information here')),
                ('confirmation_code', models.CharField(default=dtd_request.models.short_code, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('REVIEWED', 'Under Review'), ('CONTACTED', 'Contact Pending'), ('REFERRED', 'Referred'), ('CLOSED', 'Closed')], max_length=9)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_created_by', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtd_request.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.IntegerField(choices=[(1, 'Shelter/Housing'), (2, 'Employment'), (3, 'Income'), (4, 'Food and Nutrition'), (5, 'Childcare'), (6, "Children's Education"), (7, 'Adult Education'), (8, 'Healthcare'), (9, 'Life Skills'), (10, 'Family Relationships/Social Network'), (11, 'Transportation/Mobility'), (12, 'Community Involvement'), (13, 'Parenting Skills'), (14, 'Legal'), (15, 'Mental Health'), (16, 'Substance Abuse'), (17, 'Safety'), (18, 'Disability Services'), (19, 'Credit/Financial Management'), (20, 'Spirituality')], verbose_name='What kind of help are you looking for?')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtd_request.Request')),
            ],
        ),
    ]
