# Generated by Django 3.0.4 on 2020-03-22 03:39

from django.db import migrations, models
import django.db.models.deletion
import os


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_DB_NAME = os.getenv("POSTGRES_DB", "default")
        DJANGO_SU_NAME = os.getenv("DJANGO_SUPERUSER")
        DJANGO_SU_EMAIL = os.getenv("DJANGO_SU_EMAIL")
        DJANGO_SU_PASSWORD = os.getenv("DJANGO_SU_PASSWORD")

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME, email=DJANGO_SU_EMAIL, password=DJANGO_SU_PASSWORD
        )

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
