# Generated by Django 3.0.4 on 2020-03-27 02:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import questgiver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questgiver", "0000_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contact_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=200)),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")
                        ],
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("days_allowed", models.IntegerField(default=7)),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                (
                    "accepted_by_email",
                    models.EmailField(blank=True, max_length=200, null=True),
                ),
                (
                    "accepted_by_phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")
                        ],
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("retired", models.BooleanField(default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("abandoned", models.BooleanField(default=False)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                ("reposted", models.BooleanField(default=False)),
                ("reposted_at", models.DateTimeField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "email_code",
                    models.CharField(default=questgiver.models.uuid_str, max_length=36),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quest_approved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
