# Generated by Django 3.0.4 on 2020-04-06 03:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(verbose_name='Call Started')),
                ('ended_at', models.DateTimeField(verbose_name='Call Ended')),
                ('caller_number', models.CharField(help_text='###-###-####', max_length=17, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Caller Phone Number')),
                ('caller_zip', models.CharField(help_text='#####', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$')], verbose_name='Caller Zip Code')),
                ('covid_related', models.BooleanField(default=False, verbose_name='Is this call related to Covid-19?')),
                ('client_referred', models.BooleanField(default=False, verbose_name='Was this client referred to a provider?')),
                ('referral_id', models.IntegerField(blank=True, null=True, verbose_name='Referral ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_operator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
