# Generated by Django 3.0.4 on 2020-07-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtd_calls', '0006_add_ftp_call_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_source',
            field=models.TextField(blank=True, choices=[('church', 'Church/Religious Institution'), ('work', 'Workplace'), ('211', 'LINC-211'), ('radio', 'Radio Ad'), ('other', 'Other')], max_length=200, null=True, verbose_name='How did you hear about the UWMS Relief Call Center?'),
        ),
    ]
