# Generated by Django 3.0.4 on 2020-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtd_calls', '0007_call_call_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='caller_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Call Date of Birth'),
        ),
    ]
